"use client";
import {useState,useRef,useEffect,useCallback} from "react";
import {Activity,Search,ArrowUpRight,ArrowDownRight,ArrowRight,CalendarDays,ClipboardList,ChartNoAxesCombined,Heart,ShieldCheck,RefreshCw,Printer,Maximize2,Minimize2,ChevronRight,CircleHelp,Link2,Leaf,AlertCircle,SlidersHorizontal} from "lucide-react";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from "recharts";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {demoPatient,DEMO_ID,dateLabel,periodStart,LIFE_LABELS,LIFE_MAX,MSSI_LABELS,type Patient,type Entry} from "@/lib/clinical";
import {getPatient} from "@/lib/transport";
import {registerPeriodTool} from "@/lib/webmcp";
const num=(n:number|null|undefined)=>n==null?"—":String(n);
function Trend({change,kind}:{change:number|null;kind:Entry["kind"]}){
  if(change===null)return <span className="comparison neutral">이전 기록 없음</span>;
  const good=kind==="mssi"?change<0:change>0;
  return <span className={`comparison ${change===0?"neutral":good?"good":"attention"}`}>{change<0?<ArrowDownRight size={16}/>:change>0?<ArrowUpRight size={16}/>:null}{change===0?"변화 없음":`${Math.abs(change)}점 ${change>0?"상승":"감소"}`}</span>;
}
export function SummaryCard({kind,records}:{kind:Entry["kind"];records:Entry[]}){
  const latest=records.at(-1),previous=records.at(-2),change=latest?.score!=null&&previous?.score!=null?latest.score-previous.score:null;
  return <section className={`metric-card ${kind}`}><div className="metric-top"><span>{kind==="mssi"?"MSSI 기분안정성":"생활습관"}</span>{kind==="mssi"?<Activity size={20}/>:<Leaf size={20}/>}</div><div className="metric-value">{num(latest?.score)}<span>/ {kind==="mssi"?240:100}점</span></div><div className="metric-bottom"><Trend change={change} kind={kind}/><span>{previous?`${dateLabel(previous.date)} 대비`:""}</span></div><div className="metric-caption">{latest?`${dateLabel(latest.date,true)} · `:""}{kind==="mssi"?"낮을수록 증상 부담이 적음":"높을수록 생활습관 점수가 좋음"}</div></section>;
}
export function Plot({kind,records,domain,onSelect,selected}:{kind:Entry["kind"];records:Entry[];domain:[number,number];onSelect:(e:Entry)=>void;selected:Entry|null}){
  const color=kind==="mssi"?"#4769d9":"#04968b",points=records.map(e=>({...e,t:new Date(e.date).getTime()})),ticks=Array.from({length:5},(_,i)=>domain[0]+(domain[1]-domain[0])*i/4);
  return <div className="plot-row"><div className="plot-heading"><span className={`legend-dot ${kind}`}/><strong>{kind==="mssi"?"MSSI":"생활습관"}</strong><span>{kind==="mssi"?"0–240점 · 최근 2주":"0–100점 · 최근 한 달"}</span></div><div className="chart-area">{!records.length?<div className="chart-empty">이 기간에 작성한 기록이 없습니다.</div>:<ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:12,right:24,bottom:0,left:-18}}><CartesianGrid stroke="#e9eef4" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="t" type="number" domain={domain} ticks={ticks} tickFormatter={v=>dateLabel(new Date(v).toISOString())} axisLine={false} tickLine={false} tick={{fill:"#758398",fontSize:12}} minTickGap={35}/><YAxis domain={[0,kind==="mssi"?240:100]} ticks={kind==="mssi"?[0,60,120,180,240]:[0,25,50,75,100]} axisLine={false} tickLine={false} tick={{fill:"#758398",fontSize:12}}/><Tooltip cursor={{stroke:"#becbdd",strokeDasharray:"4 4"}} content={({active,payload})=>{const p=payload?.[0]?.payload as Entry|undefined;return active&&p?<div className="chart-tooltip"><span>{dateLabel(p.date,true)}</span><strong>{kind==="mssi"?"MSSI":"생활습관"} {num(p.score)}점</strong><small>점을 선택하면 상세 응답을 볼 수 있습니다</small></div>:null;}}/>{selected&&<ReferenceLine x={new Date(selected.date).getTime()} stroke="#bac6d6" strokeDasharray="4 4"/>}<Line type="linear" dataKey="score" stroke={color} strokeWidth={2.8} connectNulls={false} isAnimationActive={false} dot={(props)=>{const {cx,cy,payload}=props;return <circle key={payload.id} cx={cx} cy={cy} r={5} fill="#fff" stroke={color} strokeWidth={2} style={{cursor:"pointer"}} role="button" tabIndex={0} aria-label={`${dateLabel(payload.date,true)} ${num(payload.score)}점 상세 보기`} onClick={()=>onSelect(payload)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(payload);}}}/>;}} activeDot={{r:7,fill:color,stroke:"white",strokeWidth:3,onClick:(_,p)=>{const point=p as unknown as {payload:Entry};if(point.payload)onSelect(point.payload);}}}/></LineChart></ResponsiveContainer>}</div></div>;
}
export default function Dashboard(){
  const [patient,setPatient]=useState<Patient|null>(demoPatient),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[months,setMonths]=useState(0),[tab,setTab]=useState("overview"),[selected,setSelected]=useState<Entry|null>(null),[present,setPresent]=useState(false),[connection,setConnection]=useState(false),[help,setHelp]=useState(false);
  const request=useRef(0),searchInput=useRef<HTMLInputElement>(null),all=patient?.entries??[];
  const lastTime=all.length?Math.max(...all.map(e=>new Date(e.date).getTime())):0,firstTime=all.length?Math.min(...all.map(e=>new Date(e.date).getTime())):lastTime;
  const cutoff=periodStart(lastTime,months,firstTime);
  const filtered=all.filter(e=>new Date(e.date).getTime()>=cutoff),mssi=filtered.filter(e=>e.kind==="mssi"),life=filtered.filter(e=>e.kind==="lifestyle"),domain:[number,number]=[Math.min(cutoff,lastTime-86400000),lastTime+86400000*2];
  const latestM=mssi.at(-1),latestL=life.at(-1),firstM=mssi[0],firstL=life[0],mChange=latestM?.score!=null&&firstM?.score!=null&&mssi.length>1?latestM.score-firstM.score:null,lChange=latestL?.score!=null&&firstL?.score!=null&&life.length>1?latestL.score-firstL.score:null;
  const priority=latestM?[17,19].filter(i=>latestM.gates?.[i]===1||(latestM.items[i]??0)>0):[],improvements=latestL&&firstL&&life.length>1?LIFE_LABELS.map((label,i)=>({label,change:latestL.items[i]!=null&&firstL.items[i]!=null?latestL.items[i]!-firstL.items[i]!:0})).filter(v=>v.change!==0).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,3):[],dates=new Set(filtered.map(e=>dateLabel(e.date,true))).size,ordered=[...filtered].reverse();
  const load=useCallback(async(id:string)=>{const clean=id.trim();if(!clean){setError("환자번호를 입력해 주세요.");searchInput.current?.focus();return;}const current=++request.current;setBusy(true);setError("");setSelected(null);setPatient(null);try{const result=clean===DEMO_ID?demoPatient():await getPatient(clean);if(request.current!==current)return;setPatient(result);setMonths(0);setTab("overview");}catch(e){if(request.current===current)setError(e instanceof Error?e.message:"연결 상태를 확인해 주세요.");}finally{if(request.current===current)setBusy(false);}},[]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==="k"){e.preventDefault();searchInput.current?.focus();}if(e.key==="Escape")setPresent(false);};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);},[]);
  useEffect(()=>registerPeriodTool(value=>{setMonths(value);setSelected(null);}),[]);
  return <div className={`app-shell ${present?"presentation":""}`}><aside className="sidebar"><a className="brand" href="#"><span className="brand-symbol"><Activity size={24}/></span><span>SNUMOOD<small>기분장애클리닉</small></span></a><div className="sidebar-label">CLINICAL WORKSPACE</div><div className="nav-active"><ChartNoAxesCombined size={19}/><span>진료 경과</span><ChevronRight size={16}/></div><div className="sidebar-search"><label htmlFor="patient-search">환자번호 조회</label><form onSubmit={e=>{e.preventDefault();void load(input);}}><div className="search-field"><Search size={17}/><input ref={searchInput} id="patient-search" value={input} onChange={e=>setInput(e.target.value)} placeholder="환자번호 입력" autoComplete="off" spellCheck={false} maxLength={64}/><kbd>⌘K</kbd></div><button className="search-submit" disabled={busy} type="submit">{busy?"기록을 불러오는 중":"환자 조회"}{busy?<RefreshCw size={16} className="spinning"/>:<ArrowRight size={17}/>}</button></form><p>설문에 입력한 번호 또는 구분 문구</p></div><div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={19}/><div>의료진 전용<small>Google 시트 접근 권한으로 조회</small></div></div><button className="sidebar-link" onClick={()=>setConnection(true)}><Link2 size={16}/> 데이터 연결<ChevronRight size={14}/></button><button className="sidebar-link" onClick={()=>setHelp(true)}><CircleHelp size={16}/> 점수 읽는 방법<ChevronRight size={14}/></button><div className="institution">분당서울대학교병원<br/>기분장애클리닉</div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">의료진 공간 <ChevronRight size={13}/><strong>진료 경과</strong></div><div className="topbar-actions"><span className={`mode-badge ${patient?.demo?"demo":""}`}>{patient?.demo?"예시 데이터":patient?"환자 기록":"진료 경과"}</span><button className="icon-button" aria-label="점수 안내" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button><span className="doctor-avatar" aria-label="의료진">Dr.</span></div></header><main id="main-content"><div className="page-heading"><div><div className="eyebrow">PATIENT JOURNEY</div><h1>시간이 보여주는 변화<span className="heading-period">.</span></h1><p>기분과 생활의 흐름을, 환자와 함께 살펴보세요.</p></div><div className="page-actions"><button className="button subtle" onClick={()=>setPresent(v=>!v)}>{present?<Minimize2 size={16}/>:<Maximize2 size={16}/>} {present?"진료 화면으로":"함께 보기"}</button><button className="button subtle" onClick={()=>window.print()} disabled={!patient||!all.length}><Printer size={16}/> 인쇄</button></div></div>
    <div className="mobile-search"><form onSubmit={e=>{e.preventDefault();void load(input);}}><Search size={19}/><input aria-label="환자번호" placeholder="환자번호 입력" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off"/><button className="button primary" disabled={busy}>조회</button></form></div>
    {patient?.demo&&<div className="demo-banner"><span><span className="demo-tag">DEMO</span>현재 화면은 가상 환자의 예시입니다. 실제 진료 자료가 아닙니다.</span><button onClick={()=>{setPatient(null);setInput("");searchInput.current?.focus();}}>실제 환자 조회 <ArrowRight size={15}/></button></div>}
    {error&&<div className="error-banner" role="alert"><AlertCircle size={20}/><span>{error}</span><button onClick={()=>{setPatient(demoPatient());setError("");setInput("");}}>예시로 돌아가기</button></div>}
    {busy?<div className="empty-panel" role="status"><RefreshCw size={36} className="spinning"/><h2>환자의 기록을 불러오고 있습니다</h2><p>작성 날짜와 문항별 응답을 확인하고 있습니다.</p></div>:!patient?<div className="empty-panel"><div className="empty-symbol"><Search size={34}/></div><h2>환자의 이야기를 이어서 살펴보세요</h2><p>환자번호를 입력하면 그동안의 기분과 생활습관 기록을 볼 수 있습니다.</p><button className="button subtle" onClick={()=>{setPatient(demoPatient());setError("");}}>예시 화면 보기 <ArrowRight size={16}/></button></div>:<><section className="patient-bar"><div className="patient-identity"><span className="patient-avatar"><Heart size={23}/></span><div><span className="small-label">{patient.demo?"가상 환자":"환자번호"}</span><h2>{present?"나의 경과":patient.patientId}</h2></div></div><div className="patient-meta"><span><CalendarDays size={16}/>{all.length?`${dateLabel(new Date(firstTime).toISOString(),true)} — ${dateLabel(new Date(lastTime).toISOString(),true)}`:"기록 없음"}</span><span>전체 {all.length}건의 설문</span></div><button className="icon-button refresh" aria-label="최신 기록 새로고침" onClick={()=>void load(patient.patientId)}><RefreshCw size={17}/></button></section>
    {!all.length?<div className="empty-panel"><ClipboardList size={36}/><h2>이 번호로 작성한 기록이 없습니다</h2><p>설문에 입력한 번호가 일치하는지 확인해 주세요.</p></div>:<>{patient.warnings?.map((w,i)=><div className="data-notice" key={i}><AlertCircle size={17}/>{w}</div>)}<div className="section-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs" variant="line"><TabsTrigger value="overview">경과 한눈에</TabsTrigger><TabsTrigger value="records">전체 기록 <span className="count-chip">{filtered.length}</span></TabsTrigger></TabsList></Tabs><div className="period-control"><SlidersHorizontal size={15}/><span>기간</span>{[{v:3,t:"3개월"},{v:6,t:"6개월"},{v:12,t:"1년"},{v:0,t:"전체"}].map(p=><button key={p.v} data-period={p.v} aria-pressed={months===p.v} className={months===p.v?"active":""} onClick={()=>{setMonths(p.v);setSelected(null);}}>{p.t}</button>)}</div></div>
    <div className="metrics-grid"><SummaryCard kind="mssi" records={mssi}/><SummaryCard kind="lifestyle" records={life}/><section className="metric-card cadence"><div className="metric-top"><span>선택 기간의 기록</span><CalendarDays size={20}/></div><div className="metric-value">{dates}<span>일</span></div><div className="record-counts"><span><i className="legend-dot mssi"/>MSSI <strong>{mssi.length}회</strong></span><span><i className="legend-dot lifestyle"/>생활습관 <strong>{life.length}회</strong></span></div><div className="metric-caption">마지막 기록일을 기준으로 기간을 표시합니다</div></section></div>
    <Tabs value={tab} onValueChange={setTab}><TabsContent value="overview"><div className="analysis-grid"><section className="panel trend-panel"><div className="panel-heading"><div><h3>기분과 생활의 흐름</h3><p>같은 시간 축, 각각의 점수 척도</p></div><span className="small-label">{dateLabel(new Date(cutoff).toISOString())} — {dateLabel(new Date(lastTime).toISOString())}</span></div><Plot kind="mssi" records={mssi} domain={domain} selected={selected} onSelect={setSelected}/><Plot kind="lifestyle" records={life} domain={domain} selected={selected} onSelect={setSelected}/><div className="chart-footnote"><span>●</span> 점을 선택하면 그날의 상세 응답을 확인할 수 있습니다.</div></section><aside className="insights"><section className="insight-card"><div className="insight-heading"><span className="insight-icon"><ChartNoAxesCombined size={20}/></span><h3>함께 살펴볼 변화</h3></div><p className="insight-description">선택 기간의 첫 기록과 마지막 기록 비교</p><div className="insight-stat"><span>MSSI</span><strong className={mChange!==null&&mChange<0?"blue-text":""}>{mChange===null?"비교 기록 없음":`${Math.abs(mChange)}점 ${mChange>0?"상승":mChange<0?"감소":"유지"}`}</strong><small>{firstM&&latestM?`${num(firstM.score)} → ${num(latestM.score)}점`:"—"}</small></div><div className="insight-stat"><span>생활습관</span><strong className="teal-text">{lChange===null?"비교 기록 없음":`${Math.abs(lChange)}점 ${lChange>0?"상승":lChange<0?"감소":"유지"}`}</strong><small>{firstL&&latestL?`${num(firstL.score)} → ${num(latestL.score)}점`:"—"}</small></div><div className="talking-point"><span>진료 대화의 시작</span><p>{improvements.length?`${improvements[0].label} 점수가 ${Math.abs(improvements[0].change)}점 ${improvements[0].change>0?"높아졌":"낮아졌"}습니다. 그동안의 생활에서 달라진 점을 함께 확인해 보세요.`:"점수가 달라진 시기의 생활과 증상을 함께 확인해 보세요."}</p></div><p className="insight-note">점수의 동시 변화가 원인과 결과를 의미하지는 않습니다.</p></section><section className={`review-card ${priority.length?"flagged":""}`}><div><ClipboardList size={18}/><strong>문항 확인</strong></div><p>{priority.length?`최근 MSSI에서 ${priority.map(i=>i+1).join("·")}번 문항에 ‘예’ 응답이 있습니다.`:"최근 MSSI의 18·20번 응답을 진료 중 함께 확인하세요."}</p><button disabled={!latestM} onClick={()=>setSelected(latestM??null)}>상세 응답 보기 <ArrowUpRight size={15}/></button></section></aside></div>
    <div className="details-grid"><section className="panel"><div className="panel-heading"><div><h3>일상을 만드는 9가지 습관</h3><p>선택 기간의 최근 응답 · {latestL?dateLabel(latestL.date,true):"기록 없음"}</p></div><Leaf size={21} className="teal-text"/></div><div className="habit-list">{LIFE_LABELS.map((label,i)=><div className="habit-row" key={label}><span className="habit-number">{String(i+1).padStart(2,"0")}</span><span className="habit-name">{label}</span><div className="habit-track"><span style={{width:`${(latestL?.items[i]??0)/LIFE_MAX[i]*100}%`}}/></div><span className="habit-score">{num(latestL?.items[i])}<small> / {LIFE_MAX[i]}</small></span></div>)}</div></section><section className="panel"><div className="panel-heading"><div><h3>기분의 세부 변화</h3><p>최근 MSSI 문항 점수 · 빈도 × 심한 정도</p></div><span className="heat-scale">0 <i/> 12</span></div><div className="symptom-grid">{MSSI_LABELS.map((label,i)=>{const value=latestM?.items[i];return <button key={label} className={`symptom-cell ${i===17||i===19?"review-symptom":""}`} onClick={()=>setSelected(latestM??null)} disabled={!latestM} style={{background:value==null?"#f4f6f9":`rgba(71,105,217,${.04+value/12*.25})`}}><span>{i+1}. {label}</span><strong>{num(value)}</strong></button>;})}</div><div className="panel-note">21번 ‘우울하더라도 행동이 느려지진 않았다’는 총점에 포함하지 않습니다.</div></section></div></TabsContent>
    <TabsContent value="records"><section className="panel records-panel"><div className="panel-heading"><div><h3>날짜별 전체 기록</h3><p>같은 날 여러 번 작성한 응답도 각각 표시합니다.</p></div><span className="small-label">{ordered.length}건</span></div><Table><TableHeader><TableRow><TableHead>작성 날짜</TableHead><TableHead>설문</TableHead><TableHead>총점</TableHead><TableHead>확인 사항</TableHead><TableHead><span className="sr-only">상세 보기</span></TableHead></TableRow></TableHeader><TableBody>{ordered.map(e=><TableRow key={e.id}><TableCell className="date-cell">{dateLabel(e.date,true)}<small>{new Date(e.date).toLocaleTimeString("ko-KR",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit",hour12:false})}</small></TableCell><TableCell><span className={`record-type ${e.kind}`}>{e.kind==="mssi"?"MSSI":"생활습관"}</span></TableCell><TableCell><strong>{num(e.score)}</strong><span className="muted"> / {e.kind==="mssi"?240:100}</span></TableCell><TableCell>{e.warnings.length?<span className="attention">응답 확인 필요</span>:"—"}</TableCell><TableCell><button className="text-button" onClick={()=>setSelected(e)}>상세 보기 <ChevronRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table></section></TabsContent></Tabs><footer className="page-footer"><span>SNUMOOD · 분당서울대학교병원 기분장애클리닉</span><span>환자의 자기보고 기록 · 임상적 판단을 돕는 경과 자료</span></footer></>}</>}
    </main></div>
    <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{selected?.kind==="mssi"?"MSSI 상세 응답":"생활습관 상세 응답"}</DialogTitle><DialogDescription>{selected?dateLabel(selected.date,true):""} · {patient?.demo?"가상 예시":present?"환자 경과":patient?.patientId}</DialogDescription></DialogHeader>{selected&&<><div className={`detail-score ${selected.kind}`}><span>총점</span><strong>{num(selected.score)} <small>/ {selected.kind==="mssi"?240:100}점</small></strong></div>{selected.warnings.map(w=><p className="data-notice" key={w}>{w}</p>)}<div className="detail-table"><Table><TableHeader><TableRow><TableHead>문항</TableHead>{selected.kind==="mssi"&&<><TableHead>빈도</TableHead><TableHead>정도</TableHead></>}<TableHead>점수</TableHead></TableRow></TableHeader><TableBody>{(selected.kind==="mssi"?MSSI_LABELS:LIFE_LABELS).map((label,i)=><TableRow key={label}><TableCell>{i+1}. {label}</TableCell>{selected.kind==="mssi"&&<><TableCell>{num(selected.frequencies?.[i])}</TableCell><TableCell>{num(selected.severities?.[i])}</TableCell></>}<TableCell><strong>{num(selected.items[i])}</strong></TableCell></TableRow>)}</TableBody></Table></div>{selected.kind==="mssi"&&<p className="panel-note">21번: {selected.q21===1?"예 (느려지지 않았다)":selected.q21===0?"아니오 (느려졌다)":"응답 없음"} · 총점 제외</p>}</>}</DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>점수 읽는 방법</DialogTitle><DialogDescription>현재 환자 설문의 계산 방식과 동일합니다.</DialogDescription></DialogHeader><div className="help-section"><h3>MSSI · 0–240점</h3><p>최근 2주의 증상을 돌아보는 설문입니다. 1~20번 문항의 빈도(1~4)와 심한 정도(1~3)를 곱해 합산합니다. ‘아니오’는 0점입니다. 높은 점수는 보고된 증상 부담이 큰 것을 뜻합니다. 21번은 총점에서 제외합니다.</p><h3>생활습관 · 0–100점</h3><p>최근 한 달의 생활을 돌아보는 9개 문항입니다. 문항마다 배점이 다르며, 높은 점수는 생활습관 관리 점수가 좋은 것을 뜻합니다.</p><h3>변화를 해석할 때</h3><p>상단 카드는 선택 기간의 가장 최근 응답과 직전 응답을 비교합니다. 변화 요약은 선택 기간의 첫 응답과 마지막 응답을 비교합니다. 두 설문의 평가 기간이 다르므로 점수만으로 진단하거나 인과관계를 판단하지 않습니다.</p><div className="source-links"><a href="https://snumood.github.io/homepage/mssi.html" target="_blank" rel="noreferrer">MSSI 설문 <ArrowUpRight size={14}/></a><a href="https://snumood.github.io/homepage/ls.html" target="_blank" rel="noreferrer">생활습관 설문 <ArrowUpRight size={14}/></a></div></div></DialogContent></Dialog>
    <Dialog open={connection} onOpenChange={setConnection}><DialogContent><DialogHeader><DialogTitle>진료 자료 연결</DialogTitle><DialogDescription>Google 시트를 볼 수 있는 계정으로 조회합니다.</DialogDescription></DialogHeader><div className="help-section"><p>연결 대상은 기존 MSSI web 시트입니다. MSSI 통합데이터·시트1과 생활습관에서 환자번호가 정확히 일치하는 기록을 읽습니다.</p><p>Google 계정으로 로그인한 후 해당 시트의 보기 권한이 확인되면 사용할 수 있습니다.</p><a className="button subtle" href="https://docs.google.com/spreadsheets/d/1w6lMOTlXJQgF8qkc98j0MfzzCpNIGFnwFDHJhvwtGp4/edit" target="_blank" rel="noreferrer">원본 시트 열기 <ArrowUpRight size={16}/></a></div></DialogContent></Dialog>
  </div>;
}
