import {build} from "esbuild";
import fs from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
const root=path.dirname(fileURLToPath(import.meta.url)),out=path.dirname(root);
const api="https://script.google.com/macros/s/AKfycbxog8PeEquNmeWXL_h0FP09VVFTbXSDYkJ2wwyVVhl7mzwfjjZXlFkqAUVE8cmk4QeN/exec";
const client=await build({absWorkingDir:root,entryPoints:["patient-app/client.tsx"],bundle:true,write:false,minify:true,format:"iife",platform:"browser",target:"es2022",supported:{"template-literal":false},jsx:"automatic",define:{PATIENT_API_URL:JSON.stringify(api),"process.env.NODE_ENV":'"production"'}});
await fs.writeFile(path.join(out,"patient-bundle.js"),client.outputFiles[0].text);
const css=await postcss([tailwind()]).process(await fs.readFile(path.join(root,"app/globals.css"),"utf8"),{from:path.join(root,"app/globals.css")});
await fs.writeFile(path.join(out,"patient.css"),css.css+"\n"+await fs.readFile(path.join(root,"patient-app/patient.css"),"utf8"));
for(const name of ["patient.html","patient-auth.js"])await fs.copyFile(path.join(root,"patient-app",name),path.join(out,name));
await fs.mkdir(path.join(out,"vendor"),{recursive:true});await fs.copyFile(path.join(root,"vendor/supabase-js.js"),path.join(out,"vendor/supabase-js.js"));
const config=await fs.readFile(path.join(out,"config.js"),"utf8"),value=name=>config.match(new RegExp(`export const ${name} = [^\\n]+ \\|\\| "([^"]+)"`))[1];
const server=await build({absWorkingDir:root,entryPoints:["patient-app/server.ts"],bundle:true,write:false,format:"iife",globalName:"PatientServer",platform:"neutral",target:"es2020",define:{PATIENT_SUPABASE_URL:JSON.stringify(value("SUPABASE_URL")),PATIENT_SUPABASE_ANON_KEY:JSON.stringify(value("SUPABASE_ANON_KEY"))}});
await fs.mkdir(path.join(root,".google-build"),{recursive:true});
await fs.writeFile(path.join(root,".google-build/Code.js"),server.outputFiles[0].text+"\nfunction doGet(e){return PatientServer.doGet(e);}\nfunction doPost(e){return PatientServer.doPost(e);}\n");
await fs.copyFile(path.join(root,"patient-app/appsscript.json"),path.join(root,".google-build/appsscript.json"));
console.log("Patient web assets and Google backend build complete; backend deployment is a separate operation.");
