import {useState} from "react";
import {RefreshCw,Printer,CalendarDays,Leaf,Activity} from "lucide-react";
import {SummaryCard,Plot} from "../app/dashboard";
import {dateLabel,periodStart,LIFE_LABELS,LIFE_MAX,MSSI_LABELS,type Entry,type Patient} from "../lib/clinical";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "../components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "../components/ui/tabs";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "../components/ui/table";
const n=(value:number|null|undefined)=>value==null?"—":String(value);
export default function PatientHistory({patient,reload,busy}:{patient:Patient;reload:()=>void;busy:boolean}){
  const [months,setMonths]=useState(0),[selected,setSelected]=useState<Entry|null>(null),[tab,setTab]=useState("overview");
  const all=patient.entries,last=all.length?Date.parse(all.at(-1)!.date):Date.parse(patient.fetchedAt),first=all.length?Date.parse(all[0].date):last,cutoff=periodStart(last,months,first);
  const records=all.filter(e=>Date.parse(e.date)>=cutoff),mssi=records.filter(e=>e.kind==="mssi"),life=records.filter(e=>e.kind==="lifestyle"),latestM=mssi.at(-1),latestL=life.at(-1),domain:[number,number]=[Math.min(cutoff,last-86400000),last+172800000];
  const change=(entries:Entry[])=>entries.length>1&&entries[0].score!=null&&entries.at(-1)!.score!=null?entries.at(-1)!.score!-entries[0].score!:null;
  return <section className="patient-history"><div className="patient-section-heading"><div><span className="eyebrow">MY JOURNEY</span><h1>나의 기분과 생활</h1><p>기록이 쌓이면, 나의 변화가 보입니다.</p></div><div className="page-actions"><button className="button subtle" onClick={reload} disabled={busy}><RefreshCw size={16}/>새로고침</button><button className="button subtle" onClick={()=>window.print()} disabled={!all.length}><Printer size={16}/>인쇄</button></div></div>
    <div className="self-privacy"><span>내 계정으로 작성한 기록만 표시합니다.</span><span>{all.length}개의 기록</span></div>
    {patient.warnings?.map(w=><p className="data-notice" key={w}>{w}</p>)}
    {!all.length?<div className="empty-panel"><Activity size={34}/><h2>첫 기록을 남겨보세요</h2><p>생활습관이나 기분안정성 설문을 작성하면<br/>이곳에서 시간에 따른 변화를 볼 수 있어요.</p></div>:<>
    <div className="section-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line"><TabsTrigger value="overview">변화 보기</TabsTrigger><TabsTrigger value="records">날짜별 기록</TabsTrigger></TabsList></Tabs><div className="period-control"><CalendarDays size={16}/>{[[3,"3개월"],[6,"6개월"],[12,"1년"],[0,"전체"]].map(([value,label])=><button key={value} aria-pressed={months===value} onClick={()=>setMonths(Number(value))}>{label}</button>)}</div></div>
    <div className="patient-metrics"><SummaryCard kind="mssi" records={mssi}/><SummaryCard kind="lifestyle" records={life}/></div>
    <Tabs value={tab} onValueChange={setTab}><TabsContent value="overview"><section className="panel patient-trend"><div className="panel-heading"><div><h3>시간에 따른 변화</h3><p>두 설문의 점수 범위와 질문 기간은 서로 달라요.</p></div></div><Plot kind="mssi" records={mssi} domain={domain} onSelect={setSelected} selected={selected}/><Plot kind="lifestyle" records={life} domain={domain} onSelect={setSelected} selected={selected}/><div className="chart-footnote">점을 누르면 그날 작성한 내용을 볼 수 있어요.</div></section>
    <div className="patient-change">{([["MSSI",mssi],["생활습관",life]] as [string,Entry[]][]).map(([label,list])=>{const delta=change(list);return <div key={label}><span>{label} · 선택 기간의 첫 기록 대비</span><strong>{delta===null?"기록이 더 쌓이면 비교할 수 있어요":delta===0?"같은 점수예요":`${Math.abs(delta)}점 ${delta>0?"높아졌어요":"낮아졌어요"}`}</strong></div>;})}</div>
    <div className="details-grid"><section className="panel"><div className="panel-heading"><div><h3>나의 생활습관</h3><p>가장 최근 기록 · {latestL?dateLabel(latestL.date,true):"아직 기록이 없어요"}</p></div><Leaf size={22}/></div><div className="habit-list">{LIFE_LABELS.map((label,i)=><div className="habit-row" key={label}><span className="habit-number">{String(i+1).padStart(2,"0")}</span><span className="habit-name">{label}</span><div className="habit-track"><span style={{width:`${(latestL?.items[i]??0)/LIFE_MAX[i]*100}%`}}/></div><span className="habit-score">{n(latestL?.items[i])}<small> / {LIFE_MAX[i]}</small></span></div>)}</div></section><section className="panel"><div className="panel-heading"><div><h3>내가 기록한 기분</h3><p>가장 최근 MSSI 문항별 점수</p></div></div><div className="symptom-grid">{MSSI_LABELS.map((label,i)=><button className="symptom-cell" key={label} disabled={!latestM} onClick={()=>setSelected(latestM??null)}><span>{i+1}. {label}</span><strong>{n(latestM?.items[i])}</strong></button>)}</div><div className="panel-note">각 문항은 빈도 × 심한 정도로 계산해요. 21번은 총점에 포함하지 않아요.</div></section></div></TabsContent>
    <TabsContent value="records"><section className="panel"><div className="panel-heading"><h3>날짜별 기록</h3><span>{records.length}건</span></div><Table><TableHeader><TableRow><TableHead>작성일</TableHead><TableHead>설문</TableHead><TableHead>점수</TableHead><TableHead><span className="sr-only">응답 보기</span></TableHead></TableRow></TableHeader><TableBody>{[...records].reverse().map(e=><TableRow key={e.id}><TableCell>{dateLabel(e.date,true)}<small className="record-time">{new Date(e.date).toLocaleTimeString("ko-KR",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit"})}</small></TableCell><TableCell>{e.kind==="mssi"?"MSSI":"생활습관"}</TableCell><TableCell>{n(e.score)} / {e.kind==="mssi"?240:100}</TableCell><TableCell><button className="text-button" onClick={()=>setSelected(e)}>응답 보기</button></TableCell></TableRow>)}</TableBody></Table></section></TabsContent></Tabs>
    <p className="patient-disclaimer">점수는 스스로 돌아보기 위한 자료이며 진단을 대신하지 않습니다. 변화가 걱정되면 진료 때 함께 이야기해 주세요.</p></>}
    <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{selected?.kind==="mssi"?"기분안정성 응답":"생활습관 응답"}</DialogTitle><DialogDescription>{selected?dateLabel(selected.date,true):""} · 내가 작성한 기록</DialogDescription></DialogHeader>{selected&&<><div className={`detail-score ${selected.kind}`}><span>총점</span><strong>{n(selected.score)}<small> / {selected.kind==="mssi"?240:100}점</small></strong></div>{selected.warnings.map(w=><p className="data-notice" key={w}>{w}</p>)}<div className="detail-table"><Table><TableHeader><TableRow><TableHead>문항</TableHead>{selected.kind==="mssi"&&<><TableHead>빈도</TableHead><TableHead>정도</TableHead></>}<TableHead>점수</TableHead></TableRow></TableHeader><TableBody>{(selected.kind==="mssi"?MSSI_LABELS:LIFE_LABELS).map((label,i)=><TableRow key={label}><TableCell>{i+1}. {label}</TableCell>{selected.kind==="mssi"&&<><TableCell>{n(selected.frequencies?.[i])}</TableCell><TableCell>{n(selected.severities?.[i])}</TableCell></>}<TableCell>{n(selected.items[i])}</TableCell></TableRow>)}</TableBody></Table></div>{selected.kind==="mssi"&&<p className="panel-note">21번: {selected.q21===1?"예 (느려지지 않았다)":selected.q21===0?"아니오 (느려졌다)":"응답 없음"} · 총점 제외</p>}</>}</DialogContent></Dialog>
  </section>;
}
